# Generated by Django 5.0.4 on 2026-08-11 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='assets/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('focal_x', models.FloatField(default=50.0, help_text='X-coordinate (percentage)')),
                ('focal_y', models.FloatField(default=50.0, help_text='Y-coordinate (percentage)')),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash', max_length=64, unique=True)),
                ('srcset_paths', models.JSONField(blank=True, default=dict, help_text='Paths to optimized responsive variants')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
