---
deployment:
  tasks:
    # 1. Sync the frontend build to the root of the repository deployment path
    - /bin/cp -R frontend/dist/* ./

    # 2. Touch tmp/restart.txt to automatically restart Phusion Passenger application
    - /bin/mkdir -p tmp
    - /bin/touch tmp/restart.txt
