# Generated by Django 5.0.4 on 2026-08-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assigned_model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_groups', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('RICHTEXT', 'Rich Text'), ('REPEATER', 'Repeater'), ('NESTED_REPEATER', 'Nested Repeater'), ('SELECT', 'Select'), ('RELATION', 'Relation')], max_length=50)),
                ('name', models.CharField(help_text='Display label', max_length=255)),
                ('key', models.CharField(help_text='Machine-readable key in JSON payload', max_length=255)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='JSON schema for validation (e.g. required, max_length, sub_fields)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cms_core.customfieldgroup')),
            ],
        ),
    ]
