# Generated by Django 5.0.4 on 2026-08-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_core', '0002_customfieldgroup_customfielddefinition'),
        ('core', '0009_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
                ('noindex', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('Hero', 'Hero'), ('FeatureGrid', 'Feature Grid'), ('ComparisonTable', 'Comparison Table'), ('FAQAccordion', 'FAQ Accordion'), ('CTABanner', 'CTA Banner'), ('Testimonial', 'Testimonial'), ('ProductGrid', 'Product Grid')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Block payload corresponding to its JSON schema.')),
                ('visibility_rules', models.JSONField(blank=True, default=dict, help_text='Rules for conditional rendering.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms_core.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
