# Generated by Django 5.0.4 on 2026-08-11 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('SuperAdmin', 'Super Admin'), ('Editor', 'Editor'), ('Author', 'Author'), ('Contributor', 'Contributor'), ('SalesSupport', 'Sales Support'), ('SEOManager', 'SEO Manager')], help_text="Designates the user's operational role within the CMS.", max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
