# Generated by Django 5.0.4 on 2026-08-11 11:08

import cms_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(choices=[('Color', 'Color'), ('Typography', 'Typography'), ('Spacing', 'Spacing'), ('Other', 'Other')], default='Color', max_length=50)),
                ('key', models.CharField(help_text="Must start with '--', e.g. '--color-primary'", max_length=255, unique=True, validators=[cms_settings.models.validate_css_variable])),
                ('value', models.CharField(help_text="e.g. '#141414' or '16px'", max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('key', models.CharField(help_text="Unique identifier for the snippet, e.g. 'footer_address'", max_length=255, unique=True)),
                ('content', models.TextField(help_text='The actual content of the snippet (Plain text or HTML).')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
