# Generated by Django 5.0.4 on 2026-07-04 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Max 60 characters for optimal search engine display.', max_length=60, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('focus_keyword', models.CharField(blank=True, max_length=255, verbose_name='Focus Keyword')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Used to avoid duplicate content issues.', null=True, verbose_name='Canonical URL')),
                ('no_index', models.BooleanField(default=False, help_text='Ask search engines not to index this page.', verbose_name='No Index')),
                ('no_follow', models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.', verbose_name='No Follow')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='Open Graph Image')),
                ('schema_override', models.TextField(blank=True, help_text='Provide custom JSON-LD schema. Leaving it blank will generate the default schema.', verbose_name='JSON-LD Schema Override')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Max 60 characters for optimal search engine display.', max_length=60, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('focus_keyword', models.CharField(blank=True, max_length=255, verbose_name='Focus Keyword')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Used to avoid duplicate content issues.', null=True, verbose_name='Canonical URL')),
                ('no_index', models.BooleanField(default=False, help_text='Ask search engines not to index this page.', verbose_name='No Index')),
                ('no_follow', models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.', verbose_name='No Follow')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='Open Graph Image')),
                ('schema_override', models.TextField(blank=True, help_text='Provide custom JSON-LD schema. Leaving it blank will generate the default schema.', verbose_name='JSON-LD Schema Override')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Max 60 characters for optimal search engine display.', max_length=60, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('focus_keyword', models.CharField(blank=True, max_length=255, verbose_name='Focus Keyword')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Used to avoid duplicate content issues.', null=True, verbose_name='Canonical URL')),
                ('no_index', models.BooleanField(default=False, help_text='Ask search engines not to index this page.', verbose_name='No Index')),
                ('no_follow', models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.', verbose_name='No Follow')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='Open Graph Image')),
                ('schema_override', models.TextField(blank=True, help_text='Provide custom JSON-LD schema. Leaving it blank will generate the default schema.', verbose_name='JSON-LD Schema Override')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('camera_quantity', models.CharField(max_length=20)),
                ('coverage_type', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('additional_notes', models.TextField(blank=True)),
                ('recommended_package', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Max 60 characters for optimal search engine display.', max_length=60, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('focus_keyword', models.CharField(blank=True, max_length=255, verbose_name='Focus Keyword')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Used to avoid duplicate content issues.', null=True, verbose_name='Canonical URL')),
                ('no_index', models.BooleanField(default=False, help_text='Ask search engines not to index this page.', verbose_name='No Index')),
                ('no_follow', models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.', verbose_name='No Follow')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='Open Graph Image')),
                ('schema_override', models.TextField(blank=True, help_text='Provide custom JSON-LD schema. Leaving it blank will generate the default schema.', verbose_name='JSON-LD Schema Override')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('content', models.TextField(help_text='Rich Text Content for the blog post.')),
                ('date_published', models.DateTimeField(help_text='Editable to preserve historical legacy timestamps for SEO rankings.', verbose_name='Date Published')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Max 60 characters for optimal search engine display.', max_length=60, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('focus_keyword', models.CharField(blank=True, max_length=255, verbose_name='Focus Keyword')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Used to avoid duplicate content issues.', null=True, verbose_name='Canonical URL')),
                ('no_index', models.BooleanField(default=False, help_text='Ask search engines not to index this page.', verbose_name='No Index')),
                ('no_follow', models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.', verbose_name='No Follow')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='Open Graph Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='Open Graph Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='Open Graph Image')),
                ('schema_override', models.TextField(blank=True, help_text='Provide custom JSON-LD schema. Leaving it blank will generate the default schema.', verbose_name='JSON-LD Schema Override')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 15.00 for 15% discount', max_digits=5, verbose_name='Discount Percentage')),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-Order')], default='in_stock', max_length=20)),
                ('technical_specifications', models.JSONField(blank=True, default=dict, help_text='Store specs as Key-Value pairs: {"resolution": "4K", "lens": "2.8mm"}')),
                ('faq_builder', models.JSONField(blank=True, default=list, help_text='Nested Array of FAQs: [{"question": "...", "answer": "..."}]')),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
