# Generated by Django 5.0.4 on 2026-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wordpress_redirects'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional asset identifier', max_length=200)),
                ('file', models.ImageField(help_text='Upload raw image (PNG, JPG, JPEG, WEBP)', upload_to='assets/')),
                ('alt_text', models.CharField(help_text='Critical SEO ALT description. Cannot be empty.', max_length=255)),
                ('is_header', models.BooleanField(default=False, help_text='True if this is a primary header layout image (500KB cap), false for standard layout (200KB cap)')),
                ('srcset_data', models.JSONField(blank=True, default=dict, help_text='Stores relative paths for 400w, 800w, and 1200w variants')),
            ],
        ),
    ]
