# Generated by Django 5.0.4 on 2026-07-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="e.g. 'site_contents' or 'global_config'", max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
    ]
