# Generated by Django 5.0.4 on 2026-07-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_passwordresetotp'),
        ('redirects', '0002_alter_redirect_new_path_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='faq_builder',
            field=models.JSONField(blank=True, default=list, help_text='Nested Array of FAQs: [{"question": "...", "answer": "..."}]'),
        ),
        migrations.CreateModel(
            name='RedirectExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to temporarily disable this redirect.')),
                ('redirect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='redirects.redirect')),
            ],
        ),
    ]
