# Generated by Django 5.0.4 on 2026-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost_faq_builder_redirectextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsTxtConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='User-agent: *\nDisallow: /admin/\nDisallow: /api/\nDisallow: /search/?q=\n', help_text='The contents of your robots.txt file. Ensure you do not block the entire site accidentally.')),
            ],
            options={
                'verbose_name': 'Robots.txt Configuration',
                'verbose_name_plural': 'Robots.txt Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='is_header',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='asset_type',
            field=models.CharField(choices=[('general', 'General'), ('hero', 'Hero Layout (Max 500KB)'), ('product', 'Product (Min 800x800, Max 200KB)')], default='general', help_text='Determine optimization ceilings and dimension constraints.', max_length=20),
        ),
    ]
