# Generated by Django 5.0.4 on 2026-07-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_robotstxtconfig_remove_mediaasset_is_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('premium-cameras', 'Premium Cameras'), ('control-centers', 'Control Rooms'), ('thermal-ir', 'Thermal / IR'), ('enterprise-installations', 'Enterprise Installations')], default='premium-cameras', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('resolution', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, default='ACTIVE - SECURED', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Upload gallery image here.', null=True, upload_to='gallery/')),
            ],
        ),
    ]
